# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='name',
        ),
        migrations.AddField(
            model_name='database',
            name='desc',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='vehicle_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
