# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0002_auto_20170721_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='bill_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='database',
            name='firm',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
